### ISSUE TITLE
"Connection refused." on Mac OS and BlueBox

### ISSUE THREAD

**Issue by dpwalters** [classilla/cryanc#20]
I tried using carl following your guide on Mac OS 10.4 with BlueBox and Classilla 9.3.4b. If I enter localhost in the SSL proxy field I get "Unable to find proxy server". If I enter 127.0.0.1 in the SSL proxy field I get "Connection refused" when trying to access https sites. I even tried using your latest code from Git and I couldn't get it working. I looked at netstat output and carl is indeed listening on the port. Any ideas?

**Comment by dpwalters** [comment]
I started it with the suggested line. The output of netstat shows listening on 127.0.0.1:8765.
I do actually get a connection in Terminal if I open a connection and I can get a web-page by entering
something like "GET https://duckduckgo.com HTTPS/1.1" in there. I can view regular web-pages in Classilla (non https).
It is some type of configuration issue I'm just wondering what it is. Is it possible to get the older Safari to use carl as well?

**Comment by classilla** [comment]
Did you set `network.http.proxy.use-http-proxy-for-https` to `true` in `about:config`? Otherwise, it sounds like `carl` is working, so this isn't really a Crypto Ancienne bug at this point.

No, Safari can't be fooled in this way. It is possible to use older versions of OmniWeb, see https://oldvcr.blogspot.com/2020/11/fun-with-crypto-ancienne-tls-for.html

**Comment by classilla** [comment]
(The screenshots here might help, they're off my OS 9 system: https://oldvcr.blogspot.com/2021/03/the-final-official-release-of-classilla.html )

**Comment by dpwalters** [comment]
I actually got it working but I had to use micro_inetd_any and I had to specify the ipv4 address, not the loopback address. I think what it was doing, the computer in question has ipv6 addresses and routes on it, so it was trying to resolve 127.0.0.1 to ::1 or something and so the v4 connection was never actually happening. I would like to be able to use the loopback address, however. The ifconfig man page does not recommend just removing the v6 routes and addresses for some
reason so I'm hesitant to do that.

**Comment by classilla** [comment]
I don't have IPv6 disabled on my G5 but my local net is strictly IPv4, so there are no routes. Since Classic uses the system resolver, I suppose you could forge something in your system's `/etc/hosts` with `carl 127.0.0.1` or some such and then use pseudo-hostname `carl` as the proxy instead of `localhost`. Just guessing here.
